### ISSUE TITLE
Problem with example code

### ISSUE THREAD

**Issue by iangilman** [kevzettler/parse-magica-voxel#11]
Thank you for making this awesome library! 

When using your example code, I found a number of issues. I think this is correct:

```
var parseMagicaVoxel = require('parse-magica-voxel');
var myRequest = new Request("chr_knight.vox");
fetch(myRequest)
  .then(function (response) {
    return response.arrayBuffer();
  })
  .then(function (buffer) {
    console.log(JSON.stringify(parseMagicaVoxel(buffer)));
  });
```

**Comment by kevzettler** [comment]
@iangilman here is the diff between the example in the README and your submitted example
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/126209/186059322-4d2b7f6f-50f8-4493-a7a1-e8031e1ce150.png">


As far as I can tell the suggested changes are whitespace formatting. and then the file name `magicavoxel.vox` -> `chr_knight.vox` 

Is that your suggestion?

whitespace formatting is inconsequential and the file name is an example and subjective to what ever file name you are using locally. I'm going to close this issue let me know if theres something I'm missing.

**Comment by iangilman** [comment]
@kevzettler Apologies for not drawing attention to the actual fixes! Of course, you're right that the whitespace changes are subjective, and yeah, the file name was just what I was working with. 

The actual changes that fix errors in the code are removing the `});` on line 7 and the `};` on line 9 (they don't actually match anything), and changing `Buffer` to `buffer` on line 6 (the latter being the actual variable name).
