### ISSUE TITLE
How to use this in a browser?

### ISSUE THREAD

**Issue by Quoteme** [kevzettler/parse-magica-voxel#4]
In your README.MD it says
> Works in Browser and Node.js server environments

But there are no examples or instructions on how to achieve this. I tried browserifying your module, but I had no luck using it so far.

**Comment by kevzettler** [comment]
@Quoteme in the browser you will need to use an XLMHTTPrequest to fetch your voxel data instead of the node.js filesystem module.

something like:

```
var parseMagicaVoxel = require('parse-magica-voxel');
fetch(myRequest).then(function(response) {
    return response.arrayBuffer();
  }).then(function(buffer) {
     console.log(JSON.stringify(parseMagicaVoxel(Buffer));
    });
  });
};
```
