### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by matthewjosephtaylor** [kevzettler/parse-magica-voxel#9]
@kevzettler If you could quickly add a license file I'd really appreciate it :)

I'm creating a fork of your work here: https://github.com/matthewjosephtaylor/magica-voxels

Also, please let me know how you would like to be credited.

Thanks for the awesome work!

**Comment by matthewjosephtaylor** [comment]
I see on https://www.npmjs.com/package/parse-magica-voxel that this is an MIT licensed project. That works for me, but it still might be helpful to have this in the repo.

Thanks again! :)

**Comment by kevzettler** [comment]
added in 2543ad12ed64db079c1671774542d337c12edaa6

**Comment by matthewjosephtaylor** [comment]
@kevzettler FYI you licensed this as MIT in both npm AND inside of the package.json file prior to your commit. That is the license I'm going with on my fork. 

Not sure what the sudden move to GPL means, but I would like to note that I'm releasing my fork of your code under the prior 'more open' MIT license and will be continuing with MIT on my fork.

**Comment by kevzettler** [comment]
Ok thx. Pull requests welcome.
